version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8.6

    steps:
      - checkout
      - run: pip install -r dev-requirements.txt
      - run: tox
      - run: flake8 sendgrid_backend/

workflows:
  main:
    jobs:
      - test
