version: 2.1

orbs:
  python: rohanpm/python@1.3.0

jobs:
  test:
    executor: python/python38
    steps:
      - clone
      - run: pip install -r dev-requirements.txt
      - run: tox
      - run: flake8 sendgrid_backend/

workflows:
  main:
    jobs:
      - test
